jobs:
  job1:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Sleep Command 1
          command: |
            sleep 200
  job2:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Sleep Command 2
          command: |
            sleep 50
  job3:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Sleep Command 3
          command: |
            sleep 50
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - job1
      - job2
      - job3:
          requires:
            - job2
