jobs:
  build:
    docker:
    # Primary container image where all steps run.
     - image: cimg/base:current
    # Secondary container image on common network.
     - image: naveensi/simple-flask-app

    steps:
      # command will execute in an Ubuntu-based container
      # and can access MariaDB on localhost
      - run:  nc -vz localhost 4040
      - run: curl  localhost:4040
